### PR TITLE
Optimise raster screenshots & support Windows path separator

### PR DESCRIPTION
**Pull request by SNDST00M**
Windows uses `\` in paths, so let's use both slash separators to get the filename.

### CODE REVIEW

**Comment by SNDST00M** [comment]
Done

**Comment by SNDST00M** [comment]
Gonna also ship the new version of `dom-to-image-more`, but waiting on https://github.com/1904labs/dom-to-image-more/pull/47

If it takes a couple weeks, I'll build the min.js myself and ship the pull

**Comment by SNDST00M** [comment]
Okay I have built the library myself and it's been working great in VSC!

**Comment by jeffersonlicet** [comment]
Testing

**Comment by SNDST00M** [comment]
Bumpety bump,! Thanks

**Comment by jeffersonlicet** [comment]
I would like to find a way to include dom lib from node_modules folder

**Comment by SNDST00M** [comment]
Done

**Review by jeffersonlicet — APPROVED** [review]

**Pull request merged**
